---
- hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Maak minecraft directory aan
      file:
        path: "{{ server_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0777'
    
    - name: Plaats docker-compose.yml
      template:
        src: docker-compose.yml.j2
        dest: "{{ server_dir }}/docker-compose.yml"
    
    - name: Start Minecraft stack
      community.docker.docker_compose:
        project_src: "{{ server_dir }}"
        state: present
        detached: yes
        recreate: true
