---
- hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Restart Minecraft container
      community.docker.docker_container:
        name: minecraft
        state: started
        restart: true
