pipeline {
    agent any

    environment {
        AWS_REGION = "eu-west-1"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                withAWS(credentials: 'AWS', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        Terraform init
                    '''
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                sh '''
                    cd Terraform
                    Terraform validate
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                withAWS(credentials: 'AWS', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        Terraform plan -out=tfplan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withAWS(credentials: 'AWS', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        Terraform apply -auto-approve tfplan
                    '''
                }
            }
        }
    }
}
