pipeline {
    agent any

    environment {
        AWS_REGION = "eu-west-1"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('terraform Init') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        terraform init
                    '''
                }
            }
        }

        stage('terraform Validate') {
            steps {
                sh '''
                    cd Terraform
                    terraform validate
                '''
            }
        }

        stage('terraform Plan') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        terraform plan -out=tfplan
                    '''
                }
            }
        }

        stage('terraform Apply') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    sh '''
                        cd Terraform
                        terraform apply -auto-approve tfplan
                    '''
                }
            }
        }
    }
}
