---
- hosts: localhost
  become: true
  vars:
   ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
             - docker
             - git
        state: present

   - name: Start and enable Docker
     service:
        name: docker
        state: started
        enabled: true
   - name: Add ec2-user to docker group 
     user: 
        name: ec2-user 
        groups: docker 
        append: yes 
    
   - name: Install Docker SDK for Python
     pip: 
        name: docker 
      
   - name: Pull Minecraft Docker image 
       community.docker.docker_image: 
        name: itzg/minecraft-server 
        source: pull 
      
   - name: Run Minecraft container
     community.docker.docker_container:
        name: minecraft 
        image: itzg/minecraft-server 
        state: started 
        restart_policy: unless-stopped 
        ports: - "25565:25565" 
        env: 
        EULA: "TRUE" 
        VERSION: "1.20.1" 
        MOTD: "Welkom op mijn server" 
        MAX_PLAYERS: "10" 
        MEMORY: "512M"
